name: shop4
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  intl: ^0.15.8
  http: ^0.12.0+2
  flutter:
    sdk: flutter
  provider: ^3.0.0+1
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter




# The following section is specific to Flutter.
flutter:


  uses-material-design: true

  fonts:
     - family: Dosis
       fonts:
         - asset: Assets/Fonts/Dosis-Medium.ttf
         - weight: 500

     - family: Teko
       fonts:
          - asset: Assets/Fonts/Teko-Regular.ttf
          - weight: 700
